### ISSUE TITLE
bug: circuit builder with nand and xor is broken

### ISSUE THREAD

**Issue by kevinawalsh** [kevinawalsh/logisim-evolution#26]
nand builder can't deal with xors

**Comment by BFH-ktt1** [comment]
Maybe my push 28e5f68 gives a solution Sorry, not a solution to the Xor etc. problem, but to bugs still present in the circuitbuilder in holy cross.....

**Comment by kevinawalsh** [comment]
Mostly fixed by 35a1bef5f4231d5171f9141291611636ad3a855c
