### ISSUE TITLE
Missing Mac OSX DMG after Java 8

### ISSUE THREAD

**Issue by kevinawalsh** [kevinawalsh/logisim-evolution#29]
There is no mac-specific for releases starting at 4.0.0-hc, because we now use java 8 and the mac-specific adapters don't seem to work in java 8. Need to either find working java8 mac adapters, or consider moving to java9 or above to use newer Desktop support.

**Comment by maehne** [comment]
This has been fixed [upstream](https://github.com/reds-heig/logisim-evolution) when using OpenJDK &geq; 9. A DMG can be built using `./gradlew createDmg`.

**Comment by kevinawalsh** [comment]
Updated to Java 17.
