### ISSUE TITLE
Truthtables vertical scrollbar does not update when the truthtable gets larger than the size of the jpanel

### ISSUE THREAD

**Issue by BFH-ktt1** [kevinawalsh/logisim-evolution#34]
When adding inputs or loading a truth table from file, the vertical scrollbar does not get updated. To access the lower entries of the truth table one has to resize the window,
To update it automatically add to TableTab.java in the fuction updateTable() following line before repaint:

body.setSize(new Dimension(body.getWidth(),table.getRowCount()*cellHeight));

This does the trick.

**Comment by kevinawalsh** [comment]
Good catch, thanks. Merged.
