### ISSUE TITLE
bug? Behavior on input/output tab on MAC

### ISSUE THREAD

**Issue by BFH-ktt1** [kevinawalsh/logisim-evolution#40]
We observed on a mac-book-pro that when entering a input- or output-variable in the input-output tab that we got error messages on duplicated names (not using the enter key, just moving the mouse). I tried to reproduce this on a mac book air I just purchased last week, but was unable to produce the effect. However, I noticed a different behavior between Windows/linux environment and mac-os. I want to dive into more details, but have a an idea that it may be related to "close on focus lost" and maybe the jdk. We cross verified this with my merged code in evolution and the current source-code of holy-cross (both reacted equally).

**Comment by kevinawalsh** [comment]
I have not been able to reproduce this bug in the current code base. Input/output panels appear to be working fine on mac.
