### ISSUE TITLE
large 4-input OR gate looks funny

### ISSUE THREAD

**Issue by kevinawalsh** [kevinawalsh/logisim-evolution#50]
One of the pins is dangling in a strange way.

**Comment by BFH-ktt1** [comment]
I observed that it is the case for all gates in large form with 4-inputs, jfyi

**Comment by BFH-ktt1** [comment]
Can be fixed by adding an offset in AbstractGate.java (line 270 .. 277):
old:

    int dy;
    if ((inputs & 1) == 1) {
      dy = skipStart * (inputs - 1) + skipDist * index;
    } else {
      dy = skipStart * inputs + skipDist * index;
      if (index >= inputs / 2) dy += skipLowerEven;
    }

new:

    int dy;
    if ((inputs & 1) == 1) {
      dy = skipStart * (inputs - 1) + skipDist * index;
    } else {
      dy = skipStart * inputs + skipDist * index;
      if (index >= inputs / 2) dy += skipLowerEven;
      if (inputs == 4 && size >= 60) dy -= 10;
    }

The problem here is that we cannot make a fix that preserves back-ward compatibility as the position of the inputs will move with respect to the output.....

**Comment by kevinawalsh** [comment]
Fixed in 472a75e3e0578c98f1bda6b1a6d425b509b28119, with a warning upon file open about this backwards-incompatible change.
