### ISSUE TITLE
weird visual glitch with larger circuits [4.0.1]

### ISSUE THREAD

**Issue by ProxyPlayerHD** [kevinawalsh/logisim-evolution#57]
usually all components have gray pins when not connected and when using the poke tool you can look at the state of a wire...

well after a certain distance from the top left of the circuit this kinda stops working.

components get black/blue pins (black if pin is wider than 1 bit) and using the poke tool doesn't seem to work anymore. even when the wire is showing a high or low state the poke tool still only shows "X"s but only after a split point in a wire (the split points are always blue on single bit wires)

it's hard to explain, so here a few screenshots.
how it's supposed to be:
<img width="207" alt="javaw_2019-12-16_20-19-50" src="https://user-images.githubusercontent.com/13576843/70935885-81bf9180-2041-11ea-9aea-34b0cb52e733.png">
how it looks if far enough away:
<img width="189" alt="javaw_2019-12-16_20-20-00" src="https://user-images.githubusercontent.com/13576843/70935888-83895500-2041-11ea-8e56-5616cb418bd7.png">
both right next to eachother.
<img width="431" alt="javaw_2019-12-16_20-20-46" src="https://user-images.githubusercontent.com/13576843/70935910-8d12bd00-2041-11ea-9305-53252aac6822.png">

no idea why this is happening, i also tried it on a completely new file and it still happens. so this should be easy to reproduce.

lastly, this is purely visual, the circuits still work as expected.

**Comment by kevinawalsh** [comment]
Nice catch. This is almost certainly a fault with the "fast path grid" in CircuitState. State for any point within 2000 units of the origin is handled using a dense 2d array. This makes most simulation faster, at the cost of increased memory usage. Anything further away uses a slow path hashtable, trading off speed for reduced memory usage. That code was a quick hack to improve performance, and there must be a regression in the drawing code where the slow path is failing.

**Comment by kevinawalsh** [comment]
Fixed by c1337692098bb8c90247b49f2263182379d1b202
