### ISSUE TITLE
The HEX Editor is broken

### ISSUE THREAD

**Issue by ProxyPlayerHD** [kevinawalsh/logisim-evolution#60]
the reason i'm glad that we can finally save RAM/ROM images in other formats.

examples of what i noticed:

1. if you copy a section from the Editor you cannot directly paste it again, you first have to paste it into some text field (i just use my browser's URL bar for this) and copy it again in order to properly paste it in the HEX Editor

2. sometimes when you paste something it deletes everything after that, i learned that the hard way (but luckly i keep backups)

i'm pretty sure there is more or smaller issues like that but those 2 are the big ones i found.

**Comment by kevinawalsh** [comment]
1. This was a careless bug -- I can't imagine what I was thinking when I wrote it, or how it ever got past initial testing as it clearly could not have worked. It is fixed now in 9b24d5b729b0a525ea4cbbb6d65848ce989f40a2

2. This one I haven't been able to reproduce. If you can give me any hints as to what I can try to trigger this bug, let me know and I can reopen this.
