### ISSUE TITLE
Feature Request:  Zoom Percentage Indicator

### ISSUE THREAD

**Issue by TChapman500** [kevinawalsh/logisim-evolution#63]
I don't know why this went away, but the original Logisim would tell you what the zoom level was as a percentage of the default zoom level.  I would like to have that come back.

**Comment by kevinawalsh** [comment]
This has been added as a feature in 7db113559ae2ef01943ec3a5572c8db67a82d01a.
To see the zoom percentage, go into the window options and enable the "show coordinates and zoom percentage" option.
A pre-release including this can be found as
nightly-2023-07-11
under the releases page.
