### ISSUE TITLE
Documentation Request:  Java Attributes Tutorial

### ISSUE THREAD

**Issue by TChapman500** [kevinawalsh/logisim-evolution#64]
We need a tutorial on how to properly set the attributes to JAR components, including custom attributes.  This is so things like what's in the attached image can be avoided.  Also, so that custom attributes appear properly in the properties window.

Without `setAttributes()` call:
![FP Adder Attributes Bug](https://user-images.githubusercontent.com/4523649/83789037-27a0a000-a664-11ea-97ec-f67e04b304a2.PNG)

No entries found in StringGetter:
![FP Adder Attributes Strings](https://user-images.githubusercontent.com/4523649/83790863-d645e000-a666-11ea-9ae7-161f696ad6d7.PNG)

**Comment by kevinawalsh** [comment]
I think I'm never going to get to this one. Tutorials and documentation just don't rise to the top of the pile for me.
But I'd welcome anyone that digs through std/*/*.java to write some documentation!
