### ISSUE TITLE
Feature Request:  Register File

### ISSUE THREAD

**Issue by TChapman500** [kevinawalsh/logisim-evolution#67]
We need a register file to increase the performance of the simulation.  This register file would work exactly like the register component, except it has 1 data input and 2 data outputs, and 1 address line for each data input/output.  The address line would be limited to a value of 5 bits.  All register values should always be visible, and there should preferably be an indication on which register is selected as the input, and which are selected for which outputs.  This selection indication should account for when the same register is selected for both input and 1 output, for both outputs, and for the input and both outputs.

**Comment by kevinawalsh** [comment]
See the register file in the demo mips circuit for this component. It can be built within logisim, without needing any custom components.
