### ISSUE TITLE
Feature Request:  Dual-Phase Clocks

### ISSUE THREAD

**Issue by TChapman500** [kevinawalsh/logisim-evolution#72]
In most pin-outs that I've seen where the processor takes input from an external clock, there are two inputs which are always 180° out of phase of each other.  Because of this, I would like an output option for the clock component with values of "Single-Phase" (current/default) and "Dual-Phase" (2 outputs which are always the opposite value from each other).

**Comment by kevinawalsh** [comment]
Have you tried using two clock components, and setting the "phase offset" for one of them to 1?

**Comment by TChapman500** [comment]
Oh.
