### ISSUE TITLE
Enable Parent Version's "Evolution" circuit appearance preset

### ISSUE THREAD

**Issue by TChapman500** [kevinawalsh/logisim-evolution#91]

**Comment by kevinawalsh** [comment]
I'm not sure what this means, sorry. Is this about using the Reds-Heig style components by default?
I'm not a fan of those in most cases, I favor the classic logisim ones.
Or is this about the UI or something else?

**Comment by TChapman500** [comment]
It's basically for backwards compatibility with the Reds-Heig version of Logisim Evolution in terms of appearance.  I'm not a big fan of those things either, but I think it'll be useful for when opening Reds-Heig circuits into Holycross.
