### ISSUE TITLE
Feature Request: Higher Auto-Tick Frequencies

### ISSUE THREAD

**Issue by John-Lluch** [kevinawalsh/logisim-evolution#94]
With the ability to run the app natively on Apple Silicon I found that the app does not longer lag behind the specified Auto-Tick  Frequency, even if it is set to the max, for most average complexity projects (This was not the case when running as an Intel app under Roseta)

So I think it would be nice to have higher settings for Auto-Tick Frequency. I'm not sure by how much this can be reasonably increased, but I think the app should be able to cope just fine with at least 2048 kHz and 4096 kHz for projects where the previous limit was 1024 kHz.

(No need to say that I would be happy to perform any performance tests on my Apple Studio M1 that I may be requested )

Thanks

**Comment by kevinawalsh** [comment]
I added a few more, up to 8Mhz, in commit 1c2c01fe.

In my simple testing, with just a counter component, a clock, and a few probe components, I can reach 1.7MHz on a fairly new mac laptop.
